language: objective-c
osx_image: xcode8

script:

    - xcodebuild -project Example-Objc/FSCalendar.xcodeproj -sdk iphonesimulator -alltargets
    - xcodebuild -project Example-Swift/FSCalendarSwiftExample.xcodeproj -sdk iphonesimulator -alltargets
    - xcodebuild -project Example-TodayExtension1/Example-TodayExtension.xcodeproj -sdk iphonesimulator -alltargets
    - xcodebuild -project Example-TodayExtension2/Example-TodayExtension.xcodeproj -sdk iphonesimulator -alltargets
